### ISSUE TITLE
feat: ActivationService

### ISSUE THREAD

**Issue by azan-n** [cryptlex/web-api-client-js#17]
# Description
To allow actions supported by the Web API on Activations will be fruitful in the context of this library for both applications running on servers and browsers.

# Develop
- [ ] ActivationService
  - [ ] `createActivation()`
  - [ ] `deleteActivation()`

**Comment by adnan-kamili** [comment]
@azan-n This should be deferred for now, as these endpoints don't need an access token.

**Comment by adnan-kamili** [comment]
Will be handled by lexactivator wasm
