### ISSUE TITLE
feat: automatic retry for 429 status code

### ISSUE THREAD

**Issue by adnan-kamili** [cryptlex/web-api-client-js#25]
All the functions should have retry functionality built-in in case the API server returns 429. The header contains info related to next allowed timestamp

**Comment by adnan-kamili** [comment]
This should be helpful:

https://api.cryptlex.com/v3/docs#section/Rate-Limiting

**Comment by azan-n** [comment]
From what I understand, 
```ts
if(status === 429 && X-Rate-Limit-Remaining === 0 && (currentTime - header['X-Rate-Limit-Reset']) >= RETRY_THRESHOLD) {
    retryRequestAfter(currentTime - header['X-Rate-Limit-Reset']);
}
``` 

@adnan-kamili I suspect this might be susceptible to some sort of endless loop, or an edge case that I might not have covered.
