### ISSUE TITLE
feat: Functions for product management

### ISSUE THREAD

**Issue by jessedubbink** [cryptlex/web-api-client-js#33]
Hi o/

I think this library could also facilitate the API requests for products.

- [ ] List all products
- [ ] Create a product
- [ ] Retrieve a product
- [ ] Update a product
- [ ] Delete a product
- [ ] Download product.dat file
- [ ] Delete a product metadata field

As well as product feature flags and product versions.

**Comment by adnan-kamili** [comment]
Hi Jesse,

CRUD options related to products, product versions and feature flags is something which is done usually once in the dashboard.

Hence, we don't plan to add them in the client library.
